Update for breaking changes
b-b-blueberry/RaisedGardenBeds pull request #2
Opened 2023-02-20 04:20 UTC by FricativeMelon

2023-02-21 03:11 UTC, FricativeMelon commented
Ignore my changes to eventData.json if possible

2023-03-12 03:56 UTC, b-b-blueberry requested changes
Thanks for submitting, and sorry for taking so long to check in! It all looks good except for some fields being copied from `AssetManager` into `ModEntry`, maybe some local changes that were meant to be removed? Push up a new commit with a fix for that and it should be good to go for a Nexus release!

2023-03-12 03:56 UTC, b-b-blueberry commented on RaisedGardenBeds/ModEntry.cs
> +        internal static ModEntry Instance;
Did you mean to copy these fields from `AssetManager`? They appear to be defined in both files.

2023-03-12 03:56 UTC, b-b-blueberry commented on RaisedGardenBeds/AssetManager.cs
Existing fields also defined in `ModEntry`

2023-03-13 00:19 UTC, FricativeMelon commented
Made changes!

2023-03-13 00:21 UTC, FricativeMelon commented
Wait it has errors in game, let me take a look!

2023-03-13 00:44 UTC, FricativeMelon commented
False alarm, everything seems to be working fine!

2023-03-17 13:01 UTC, b-b-blueberry approved these changes
Looks perfect, thanks again!

2023-03-17 13:03 UTC, merged